language: python
python:
  - 3.6

env:
  matrix:
    - DJANGO=1.11
    - DJANGO=2.2

install:
  - pip install --upgrade pip
  - pip install django==$DJANGO
  - CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal pip install 'gdal<1.11'
  - pip install codecov coverage black isort flake8 twine

addons:
  apt:
    packages:
      - gdal-bin
      - libgdal-dev

script:
 - black --check .
 - flake8 --max-line-length=88 .
 - isort --recursive --check-only --diff geowidgets tests
 - ./setup.py sdist bdist_wheel
 - twine check dist/*
 - coverage run --include="./*" --omit="docs/","*/tests/*","*/tests.py","setup.py" ./setup.py test

after_success:
  - codecov
